before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - "export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start"
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: RW998Vov5qZx2FxKFqmE011YKFHQ+3TCcBhcQ+y6Kaj1BO3+X3a5yNOeeXpLCqFNbQoIgnV5QehLRTFexLdKhR1Gwfnx5LOGl8lUALaMu9IPTmKxEdCsdZTzCK5gxFfPpbbXA7zrZvA/gD3Uh3pwTzjTYN8hJvsTBd1VcXrlh0Nw9C8NuVrTb++VAjiSK40/6k24YmJPDJtfYvjc2Spqp1CNXJVDnsqSH5mJIolwB4caFAQZjAOfo1y2N6me5x+aE9DMJZQQCDtLe1wWMAUkAzM6WNupCF8ntZaGaj6BpGnNPJ9K1+zPAuAtR6EULIxtsZPq8+ksI5bA0joExyYw0sw5WBuTLiBg/XKoIoH5vCpgA0NzzD1Edp47ckdFoaNlKBb+FE5dGxvMpCbWaVjZed3pl2fSuP+UskymggKzpOhmZd5hWPlJPSeR16+iob2PfBP/crYJETslJQ576buhjwpZf8FrGAwnaUnecTdAcey/Y2TINEnDj2Ar5bVEC0yMkEswPsvlYmorYSjK0Ppl7Vjg2jcpp+ekZAlh2SqG9d4wQznxPGA2xnxKsLZztKowkfCB/Od6hSR74ID+m4mpWQ+bZQxq3tiSHqHceP3YiibHOkweNDp3hjLQj8PzOU752di6T1sxd8z2dT21kXj0c8+JEkqQ+uY5B4zSirnZg2w= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml

language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
